AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String
    Default: ecs-fargate-cfn
    

Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Ref Prefix


Outputs:
  RepositoryName:
    Value: !Ref Repository
    Export:
      Name: !Sub "${Prefix}-RepositoryName"
